[project]
name = "stock-pred-end2end-agentic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.40.0",
    "dagshub>=0.6.3",
    "feast[redis]>=0.60.0",
    "fastapi>=0.115.0",
    "joblib>=1.4.2",
    "chromadb>=1.0.15",
    "langchain-community>=0.3.0",
    "langchain-core>=0.3.0",
    "langchain-ollama>=0.3.0",
    "langgraph>=0.5.0",
    "mlflow>=3.10.1",
    "pandas>=2.2.0",
    "prometheus-client>=0.21.0",
    "prometheus-fastapi-instrumentator>=7.0.0",
    "psutil>=6.1.0",
    "pydantic>=2.10.0",
    "pyarrow>=20.0.0",
    "python-dotenv>=1.1.0",
    "redis>=4.6,<5",
    "requests>=2.32.0",
    "scikit-learn>=1.7.0",
    "torch>=2.10.0",
    "uvicorn>=0.34.0",
    "yfinance>=1.2.0",
    "streamlit>=1.55.0",
]


