apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: stock-pred
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: stock-pred-secrets
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "300m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: stock-pred
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: grafana
