apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: stock-pred
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis/redis-stack:latest
        ports:
        - containerPort: 6379
        - containerPort: 8001
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: stock-pred
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  - name: redis-insight
    port: 8001
    targetPort: 8001
  selector:
    app: redis
