apiVersion: v1
kind: Secret
metadata:
  name: stock-pred-secrets
  namespace: stock-pred
type: Opaque
stringData:
  AWS_REGION: ap-south-1
  BEDROCK_CHAT_MODEL_ID: openai.gpt-oss-20b-1:0
  BEDROCK_EMBED_MODEL_ID: amazon.titan-embed-text-v1
  NEWSAPI_KEY: ""
  FMI_API_KEY: ""
  DAGSHUB_USER_NAME: ""
  DAGSHUB_REPO_NAME: ""
  DAGSHUB_TOKEN: ""
  MLFLOW_TRACKING_URI: ""
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: admin

